/*
 * This file is part of the Scandit Data Capture SDK
 *
 * Copyright (C) 2025- Scandit AG. All rights reserved.
 */

import 'package:scandit_flutter_datacapture_core/scandit_flutter_datacapture_core.dart';

import 'scanned_component.dart';
import 'scanned_component_identifier.dart';
import 'text_identifier.dart';

class ScannedText implements ScannedComponent<TextIdentifier> {
  final ScannedComponentIdentifier _identifier;
  final TextIdentifier _definitionIdentifier;
  final Quadrilateral _location;
  final String _text;

  ScannedText._(this._identifier, this._definitionIdentifier, this._location, this._text);

  @override
  ScannedComponentIdentifier get identifier => _identifier;

  @override
  TextIdentifier get definitionIdentifier => _definitionIdentifier;

  @override
  Quadrilateral get location => _location;

  String get text => _text;

  factory ScannedText.fromJSON(Map<String, dynamic> json) {
    String text = '';
    if (json['text'] is Map<String, dynamic>) {
      text = (json['text'] as Map<String, dynamic>)['text'] as String;
    } else {
      text = json['text'] as String;
    }

    return ScannedText._(
      // The identifier of the scanned component. Randomly generated by the SDK.
      ScannedComponentIdentifier.fromJSON(json['identifier']),
      // The identifier of the text definition. This is the one used when setting up the text definition.
      TextIdentifier.fromJSON(json['definitionId']),
      Quadrilateral.fromJSON(json['location']),
      text,
    );
  }
}
