/*
 * This file is part of the Scandit Data Capture SDK
 *
 * Copyright (C) 2025- Scandit AG. All rights reserved.
 */

import 'package:scandit_flutter_datacapture_core/scandit_flutter_datacapture_core.dart';

import '../../scandit_flutter_datacapture_barcode.dart';

class ScannedBarcode implements ScannedComponent<BarcodeIdentifier> {
  final ScannedComponentIdentifier _identifier;
  final BarcodeIdentifier _definitionIdentifier;
  final Quadrilateral _location;
  final Symbology _symbology;
  final String? _payloadString;
  final String? _addOnPayloadString;
  final String? _compositePayloadString;
  final bool _isGS1DataCarrier;
  final CompositeFlag _compositeFlag;
  final bool _isColorInverted;
  final int _symbolCount;
  final int _frameId;
  final bool _isStructuredAppend;

  ScannedBarcode._(
    this._identifier,
    this._definitionIdentifier,
    this._location,
    this._symbology,
    this._payloadString,
    this._addOnPayloadString,
    this._compositePayloadString,
    this._isGS1DataCarrier,
    this._compositeFlag,
    this._isColorInverted,
    this._symbolCount,
    this._frameId,
    this._isStructuredAppend,
  );

  @override
  ScannedComponentIdentifier get identifier => _identifier;

  @override
  BarcodeIdentifier get definitionIdentifier => _definitionIdentifier;

  @override
  Quadrilateral get location => _location;

  Symbology get symbology => _symbology;

  String? get payloadString => _payloadString;

  String? get addOnPayloadString => _addOnPayloadString;

  String? get compositePayloadString => _compositePayloadString;

  bool get isGS1DataCarrier => _isGS1DataCarrier;

  CompositeFlag get compositeFlag => _compositeFlag;

  bool get isColorInverted => _isColorInverted;

  int get symbolCount => _symbolCount;

  int get frameId => _frameId;

  bool get isStructuredAppend => _isStructuredAppend;

  factory ScannedBarcode.fromJSON(Map<String, dynamic> json) {
    final barcode = json['barcode'] as Map<String, dynamic>;
    return ScannedBarcode._(
      // The identifier of the scanned component. Randomly generated by the SDK.
      ScannedComponentIdentifier.fromJSON(json['identifier'] as String),
      // The identifier of the barcode definition. This is the one used when setting up the barcode definition.
      BarcodeIdentifier.fromJSON(json['definitionId'] as String),
      Quadrilateral.fromJSON(json['location']),
      SymbologySerializer.fromJSON(barcode['symbology'] as String),
      barcode['payloadString'] as String?,
      barcode['addOnPayloadString'] as String?,
      barcode['compositePayloadString'] as String?,
      barcode['isGS1DataCarrier'] as bool? ?? false,
      CompositeFlagDeserializer.fromJSON(barcode['compositeFlag'] as String),
      barcode['isColorInverted'] as bool,
      (barcode['symbolCount'] as num).toInt(),
      (barcode['frameId'] as num).toInt(),
      barcode['isStructuredAppend'] as bool,
    );
  }
}
